services:
  - type: web
    name: job-portal-backend
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CLIENT_URL
        value: http://localhost:5173,https://job-portal-frontend-j3z4.onrender.com
      - key: MONGO_URI
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: CLOUD_NAME
        sync: false
      - key: API_KEY
        sync: false
      - key: API_SECRET
        sync: false
      - key: MAX_FILE_SIZE_BYTES
        value: 5242880

  - type: web
    name: job-portal-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_BASE_URL
        value: https://job-portal-backend-3p8v.onrender.com/api/v1
